"use client";

/**
 * HelpButton — floating ? pill that opens a LAC-powered contextual help sheet.
 *
 * Reads /lac/lac-data.json (generated by `lac export --all`) and surfaces
 * the user-facing userGuide + knownLimitations for the current screen's features.
 *
 * Usage:
 *   <HelpButton featureKeys={['odio-2026-006']} />
 *
 * The parent (AuthShell / PageLayout) resolves featureKeys from ROUTE_FEATURES.
 */

import { useState, useCallback } from "react";
import { BottomSheet } from "@/components/ui/BottomSheet";
import { getLacFeature, type LacFeatureEntry } from "@/lib/lacData";

interface HelpButtonProps {
  featureKeys: string[];
}

type ViewTab = "user" | "dev";

function mdToHtml(md: string): string {
  return md
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/`(.+?)`/g, "<code>$1</code>")
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    .replace(/(<li>.*<\/li>\n?)+/g, (m) => `<ul>${m}</ul>`)
    .replace(/\n\n/g, "</p><p>")
    .replace(/^(?!<[hul])/gm, "")
    .trim();
}

function FeatureCard({
  feature,
  view,
}: {
  feature: LacFeatureEntry;
  view: ViewTab;
}) {
  const guideUrl = `/lac/lac-guide.html#${feature.featureKey}`;

  return (
    <div className="border border-zinc-700 rounded-lg p-4 mb-4 last:mb-0">
      <div className="flex items-start justify-between gap-2 mb-3">
        <div>
          <h3 className="font-semibold text-white text-sm">{feature.title}</h3>
          <span className="text-xs text-zinc-400">{feature.domain}</span>
        </div>
        <a
          href={guideUrl}
          target="_blank"
          rel="noreferrer"
          className="text-xs text-amber-400 hover:text-amber-300 whitespace-nowrap shrink-0"
        >
          Full guide →
        </a>
      </div>

      {view === "user" && feature.views.user && (
        <div className="space-y-3">
          {feature.views.user.userGuide && (
            <div
              className="text-sm text-zinc-300 prose prose-invert prose-sm max-w-none
                         [&_h2]:text-sm [&_h2]:font-semibold [&_h2]:text-white [&_h2]:mt-3 [&_h2]:mb-1
                         [&_h3]:text-xs [&_h3]:font-medium [&_h3]:text-zinc-300 [&_h3]:mt-2 [&_h3]:mb-1
                         [&_ul]:pl-4 [&_li]:my-0.5 [&_code]:bg-zinc-800 [&_code]:px-1 [&_code]:rounded
                         [&_p]:my-1.5"
              dangerouslySetInnerHTML={{
                __html: mdToHtml(feature.views.user.userGuide),
              }}
            />
          )}
          {feature.views.user.knownLimitations &&
            feature.views.user.knownLimitations.length > 0 && (
              <div className="bg-amber-950/40 border border-amber-800/40 rounded-md p-3">
                <p className="text-xs font-semibold text-amber-400 mb-1.5">
                  Gotchas
                </p>
                <ul className="space-y-1">
                  {feature.views.user.knownLimitations.map((lim, i) => (
                    <li key={i} className="text-xs text-zinc-300 flex gap-2">
                      <span className="text-amber-500 shrink-0">•</span>
                      <span>{lim}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}
        </div>
      )}

      {view === "dev" && feature.views.dev && (
        <div className="space-y-3">
          {feature.views.dev.componentFile && (
            <div className="flex items-center gap-2">
              <span className="text-xs text-zinc-400">Component</span>
              <code className="text-xs bg-zinc-800 text-amber-300 px-2 py-0.5 rounded font-mono">
                {feature.views.dev.componentFile}
              </code>
            </div>
          )}
          {feature.views.dev.decisions && feature.views.dev.decisions.length > 0 && (
            <div>
              <p className="text-xs font-semibold text-zinc-400 mb-1.5">Key decisions</p>
              <ul className="space-y-1.5">
                {feature.views.dev.decisions.slice(0, 3).map((d, i) => (
                  <li key={i} className="text-xs text-zinc-300">
                    <span className="text-zinc-500 mr-1">{d.date}</span>
                    {d.choice}
                  </li>
                ))}
              </ul>
            </div>
          )}
          {feature.externalDependencies && feature.externalDependencies.length > 0 && (
            <div>
              <p className="text-xs font-semibold text-zinc-400 mb-1.5">Depends on</p>
              <div className="flex flex-wrap gap-1.5">
                {feature.externalDependencies.map((dep) => (
                  <a
                    key={dep}
                    href={`/lac/lac-guide.html#${dep}`}
                    target="_blank"
                    rel="noreferrer"
                    className="text-xs bg-zinc-800 text-zinc-300 hover:text-white px-2 py-0.5 rounded font-mono"
                  >
                    {dep}
                  </a>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

export function HelpButton({ featureKeys }: HelpButtonProps) {
  const [open, setOpen] = useState(false);
  const [view, setView] = useState<ViewTab>("user");
  const [features, setFeatures] = useState<LacFeatureEntry[]>([]);
  const [loading, setLoading] = useState(false);

  const handleOpen = useCallback(async () => {
    setOpen(true);
    if (features.length > 0) return;

    setLoading(true);
    try {
      const results = await Promise.all(featureKeys.map((k) => getLacFeature(k)));
      setFeatures(results.filter((f): f is LacFeatureEntry => f !== null));
    } catch {
      // Silently fail — lac-data.json may not be present in dev
    } finally {
      setLoading(false);
    }
  }, [featureKeys, features.length]);

  if (featureKeys.length === 0) return null;

  return (
    <>
      {/* Floating ? pill */}
      <button
        onClick={handleOpen}
        aria-label="Feature help"
        className="fixed top-4 right-4 z-40 flex items-center gap-1.5 bg-zinc-800/90 hover:bg-zinc-700
                   border border-zinc-600 text-zinc-300 hover:text-white text-xs font-medium
                   px-2.5 py-1.5 rounded-full shadow-lg backdrop-blur-sm transition-colors"
      >
        <span className="text-amber-400 font-bold">?</span>
        <span className="hidden sm:inline">Help</span>
      </button>

      {/* Help sheet */}
      <BottomSheet
        open={open}
        onClose={() => setOpen(false)}
        title="Feature Help"
      >
        <div className="flex flex-col h-full min-h-0">
          {/* Tab bar */}
          <div className="flex gap-1 px-4 pb-3 border-b border-zinc-700 shrink-0">
            <button
              onClick={() => setView("user")}
              className={`px-3 py-1.5 text-xs font-medium rounded-md transition-colors ${
                view === "user"
                  ? "bg-amber-500/20 text-amber-300 border border-amber-500/30"
                  : "text-zinc-400 hover:text-zinc-300"
              }`}
            >
              User Guide
            </button>
            <button
              onClick={() => setView("dev")}
              className={`px-3 py-1.5 text-xs font-medium rounded-md transition-colors ${
                view === "dev"
                  ? "bg-amber-500/20 text-amber-300 border border-amber-500/30"
                  : "text-zinc-400 hover:text-zinc-300"
              }`}
            >
              Dev
            </button>
          </div>

          {/* Content */}
          <div className="flex-1 overflow-y-auto px-4 py-3">
            {loading && (
              <p className="text-sm text-zinc-500 text-center py-6">
                Loading help…
              </p>
            )}
            {!loading && features.length === 0 && (
              <p className="text-sm text-zinc-500 text-center py-6">
                Help not available for this page.
              </p>
            )}
            {!loading &&
              features.map((f) => (
                <FeatureCard key={f.featureKey} feature={f} view={view} />
              ))}
          </div>
        </div>
      </BottomSheet>
    </>
  );
}
