#!/usr/bin/env node
/**
 * component-map.js — Component file reference for Odio
 *
 * Reads features JSON array from stdin (workspace scope, filtered to frozen+active).
 * Groups features by domain, shows componentFile → feature mapping.
 *
 * Output: Markdown table — useful for code navigation and onboarding.
 */

let raw = ''
process.stdin.on('data', chunk => { raw += chunk })
process.stdin.on('end', () => {
  const features = JSON.parse(raw)

  const DOMAIN_ORDER = [
    'app-shell', 'auth', 'recording', 'editing', 'sessions',
    'versioning', 'collaboration', 'band', 'render', 'storage'
  ]
  const STATUS_EMOJI = { frozen: '🔒', active: '🟡', draft: '⚪', deprecated: '❌' }

  const byDomain = {}
  for (const f of features) {
    const d = f.domain || 'misc'
    if (!byDomain[d]) byDomain[d] = []
    byDomain[d].push(f)
  }

  const orderedDomains = [
    ...DOMAIN_ORDER.filter(d => byDomain[d]),
    ...Object.keys(byDomain).filter(d => !DOMAIN_ORDER.includes(d)),
  ]

  const lines = []
  lines.push(`# Odio — Component Map`)
  lines.push(``)
  lines.push(`> Generated by \`lac gen --generator component-map\`  `)
  lines.push(`> ${features.length} features · maps featureKey → componentFile`)
  lines.push(``)

  for (const domain of orderedDomains) {
    const domFeatures = byDomain[domain].sort((a, b) => (a.priority ?? 99) - (b.priority ?? 99))
    const label = domain.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase())
    lines.push(`## ${label}`)
    lines.push(``)
    lines.push(`| Status | Feature | Key | Component File |`)
    lines.push(`|--------|---------|-----|----------------|`)

    for (const f of domFeatures) {
      const emoji = STATUS_EMOJI[f.status] || '·'
      const file = f.componentFile
        ? f.componentFile.split(',').map(s => `\`${s.trim()}\``).join(', ')
        : '_not set_'
      const title = f.title.replace(/\|/g, '\\|')
      lines.push(`| ${emoji} | ${title} | \`${f.featureKey}\` | ${file} |`)
    }
    lines.push(``)
  }

  lines.push(`---`)
  lines.push(``)
  lines.push(`**Legend:** 🔒 frozen · 🟡 active · ⚪ draft`)
  lines.push(``)
  lines.push(`> To update \`componentFile\` on a feature: \`lac fill --fields componentFile\` in the feature directory.`)

  process.stdout.write(lines.join('\n'))
})
