#!/usr/bin/env node
/**
 * domain-wiki.js — Odio domain-grouped markdown wiki
 *
 * Reads features JSON array from stdin (workspace scope, from lac gen --generator domain-wiki).
 * Groups features by domain, outputs a structured Markdown document.
 *
 * Sections per feature:
 *   - Problem
 *   - Analysis (if present)
 *   - Key Decisions
 *   - Implementation (if present)
 *   - Known Limitations
 */

let raw = ''
process.stdin.on('data', chunk => { raw += chunk })
process.stdin.on('end', () => {
  const features = JSON.parse(raw)

  const DOMAIN_ORDER = [
    'app-shell', 'auth', 'recording', 'editing', 'sessions',
    'versioning', 'collaboration', 'band', 'render', 'storage', 'misc'
  ]
  const DOMAIN_LABELS = {
    'app-shell': 'App Shell & Navigation',
    'auth': 'Authentication & Access',
    'recording': 'Recording',
    'editing': 'Editing & Cut Regions',
    'sessions': 'Sessions & Clips',
    'versioning': 'Versioning & Freeze',
    'collaboration': 'Collaboration',
    'band': 'Bands',
    'render': 'Render & Export',
    'storage': 'Storage & Drive',
    'misc': 'Miscellaneous',
  }

  const STATUS_EMOJI = { frozen: '🔒', active: '🟡', draft: '⚪', deprecated: '❌' }

  // Group by domain
  const byDomain = {}
  for (const f of features) {
    const d = f.domain || 'misc'
    if (!byDomain[d]) byDomain[d] = []
    byDomain[d].push(f)
  }

  const lines = []
  lines.push(`# Odio — Domain Wiki`)
  lines.push(``)
  lines.push(`> Generated by \`lac gen --generator domain-wiki\`  `)
  lines.push(`> ${features.length} features across ${Object.keys(byDomain).length} domains`)
  lines.push(``)

  // TOC
  lines.push(`## Table of Contents`)
  lines.push(``)
  const orderedDomains = [
    ...DOMAIN_ORDER.filter(d => byDomain[d]),
    ...Object.keys(byDomain).filter(d => !DOMAIN_ORDER.includes(d)),
  ]
  for (const domain of orderedDomains) {
    const label = DOMAIN_LABELS[domain] || domain
    const count = byDomain[domain].length
    lines.push(`- [${label}](#${domain}) (${count})`)
  }
  lines.push(``)
  lines.push(`---`)
  lines.push(``)

  for (const domain of orderedDomains) {
    const domainFeatures = byDomain[domain].sort((a, b) => (a.priority ?? 99) - (b.priority ?? 99))
    const label = DOMAIN_LABELS[domain] || domain
    lines.push(`## ${label} {#${domain}}`)
    lines.push(``)
    lines.push(`_${domainFeatures.length} feature${domainFeatures.length !== 1 ? 's' : ''}_`)
    lines.push(``)

    for (const f of domainFeatures) {
      const statusEmoji = STATUS_EMOJI[f.status] || '·'
      lines.push(`### ${statusEmoji} ${f.title}`)
      lines.push(``)
      lines.push(`\`${f.featureKey}\` · **${f.status}**${f.priority ? ` · P${f.priority}` : ''}${f.componentFile ? ` · \`${f.componentFile}\`` : ''}`)
      lines.push(``)

      if (f.problem) {
        lines.push(`**Problem:** ${f.problem}`)
        lines.push(``)
      }

      if (f.analysis) {
        lines.push(`**Analysis:**`)
        lines.push(``)
        lines.push(f.analysis)
        lines.push(``)
      }

      if (f.implementation) {
        lines.push(`**Implementation:**`)
        lines.push(``)
        lines.push(f.implementation)
        lines.push(``)
      }

      if (f.decisions && f.decisions.length > 0) {
        lines.push(`**Key Decisions:**`)
        lines.push(``)
        for (const d of f.decisions) {
          lines.push(`- **${d.decision}**`)
          lines.push(`  > ${d.rationale}`)
          if (d.alternativesConsidered && d.alternativesConsidered.length > 0) {
            lines.push(`  > _Alternatives considered: ${d.alternativesConsidered.join(', ')}_`)
          }
        }
        lines.push(``)
      }

      if (f.knownLimitations && f.knownLimitations.length > 0) {
        lines.push(`**Known Limitations:**`)
        for (const lim of f.knownLimitations) {
          lines.push(`- ${lim}`)
        }
        lines.push(``)
      }

      if (f.userGuide) {
        lines.push(`**User Guide:** ${f.userGuide}`)
        lines.push(``)
      }

      if (f.tags && f.tags.length > 0) {
        lines.push(`_Tags: ${f.tags.join(', ')}_`)
        lines.push(``)
      }

      lines.push(`---`)
      lines.push(``)
    }
  }

  process.stdout.write(lines.join('\n'))
})
